# Generated by Django 3.1.6 on 2021-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
