# Generated by Django 3.1.6 on 2021-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profilemodel_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='title',
            field=models.CharField(blank=True, error_messages={'max_length': 'Please make sure Title does not exceed 50 characters.'}, max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.URLField(blank=True, error_messages={'max_length': 'Please make sure Link does not exceed 10000 characters.'}, max_length=10000, verbose_name='Profile picture link'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, error_messages={'max_length': 'Please make sure Phone Number does not exceed 10 numbers.'}, max_length=10, verbose_name='Phone number'),
        ),
    ]
